UILISTS-205: Lists > Errors when query includes a deleted custom field
folio-org/ui-lists pull request #232
Opened 2024-12-13 11:23 UTC by UladzislauKutarkin

https://folio-org.atlassian.net/browse/UILISTS-205

Here we added translation for errors when custom fields were deleted.

2024-12-13 19:19 UTC, ncovercash requested changes
This does not accomplish the goal? The ticket is to make it possible to save the list with invalid fields, not change the error message.

Per the ticket, a new error code may be added on the backend that translations can be added for, but that's later

2024-12-15 18:57 UTC, ncovercash approved these changes

2024-12-16 08:13 UTC, UladzislauKutarkin commented
> This does not accomplish the goal? The ticket is to make it possible to save the list with invalid fields, not change the error message.
> 
> Per the ticket, a new error code may be added on the backend that translations can be added for, but that's later

Discussed offline

2024-12-16 12:39 UTC, mariia-aloshyna approved these changes

2024-12-17 07:31 UTC, merged