Permission handling
folio-org/ui-lists pull request #26
Opened 2023-09-25 20:41 UTC by ryandberger

- Fulfills [UILISTS-7](https://issues.folio.org/browse/UILISTS-7)
- Added handlers for buttons and URL routes to disable if user does not have needed permissions

2023-09-26 11:46 UTC, mweaver-ebsco approved these changes

2023-09-26 13:04 UTC, SergeYvas requested changes

2023-09-26 13:04 UTC, SergeYvas commented on src/index.tsx
> +            <IfPermission perm="lists.collection.get">
Let's keep all permissions names in separate enum and reuse everywhere as a constant

2023-09-26 13:07 UTC, SergeYvas commented
We need to cover the logic of adding/hiding buttons depending on permissions by tests because new logic is not covered.

2023-09-28 12:55 UTC, SergeYvas approved these changes

2023-09-28 13:18 UTC, merged